---

- name: install percona-server
  pkgin: name=percona-server state=present

- name: symlink mysql configuration
  file: src=/opt/local/etc/my.cnf dest=/etc/my.cnf owner=mysql group=mysql state=link

- name: install percona-toolkit 
  pkgin: name=percona-toolkit state=present

- name: install percona56-xtrabackup
  pkgin: name=percona56-xtrabackup state=present
